### ISSUE TITLE
tests are not running

### ISSUE THREAD

**Issue by pwmcintyre** [confluentinc/schema-registry-images#61]
hi - i'm trying to run the schema registry locally and cannot

i figure the tests in this repo should work, but they're also failing for me

what am i missing? seeking advice

when i run this compose file locally:
https://github.com/confluentinc/schema-registry-images/blob/0943371f34a68a51e06efeea3fb839f92b31bfe8/schema-registry/test/fixtures/standalone-config.yml

via:
```shell
docker compose up -d
```

no schema registries actually start:

```shell
$ docker ps -a
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                       PORTS                          NAMES
c480ea2fb841   confluentinc/cp-zookeeper:latest             "/etc/confluent/dock…"   3 minutes ago    Up 3 minutes                 2181/tcp, 2888/tcp, 3888/tcp   tmpxsbalwejeu-zookeeper-1
570f4dcd7454   confluentinc/cp-schema-registry:latest       "/etc/confluent/dock…"   3 minutes ago    Exited (1) 2 minutes ago                                    tmpxsbalwejeu-default-config-kafka-1
4322299c57de   confluentinc/cp-kafka:latest                 "/etc/confluent/dock…"   3 minutes ago    Up 3 minutes                 9092/tcp                       tmpxsbalwejeu-kafka-1
824a53ebd367   confluentinc/cp-schema-registry:latest       "/etc/confluent/dock…"   3 minutes ago    Exited (1) 3 minutes ago                                    tmpxsbalwejeu-failing-config-host-name-1
d23a0a607f81   confluentinc/cp-schema-registry:latest       "/etc/confluent/dock…"   3 minutes ago    Exited (1) 3 minutes ago                                    tmpxsbalwejeu-default-config-1
68f273015b18   confluentinc/cp-schema-registry:latest       "/etc/confluent/dock…"   3 minutes ago    Exited (1) 3 minutes ago                                    tmpxsbalwejeu-failing-config-1
```

i get these errors

default-config-kafka-1
```
2023-02-06 22:34:08 [2023-02-06 11:34:08,170] ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication)
2023-02-06 22:34:08 io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryInitializationException: io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryTimeoutException: Timed out waiting for join group to complete
2023-02-06 22:34:08     at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:334)
2023-02-06 22:34:08     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:75)
2023-02-06 22:34:08     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:90)
2023-02-06 22:34:08     at io.confluent.rest.Application.configureHandler(Application.java:285)
2023-02-06 22:34:08     at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:270)
2023-02-06 22:34:08     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
2023-02-06 22:34:08     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
2023-02-06 22:34:08 Caused by: io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryTimeoutException: Timed out waiting for join group to complete
2023-02-06 22:34:08     at io.confluent.kafka.schemaregistry.leaderelector.kafka.KafkaGroupLeaderElector.init(KafkaGroupLeaderElector.java:211)
2023-02-06 22:34:08     at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:329)
2023-02-06 22:34:08     ... 6 more
```

default-config-1
```
2023-02-06 22:33:07 [2023-02-06 11:33:07,344] ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain)
2023-02-06 22:33:07 org.apache.kafka.common.config.ConfigException: No supported Kafka endpoints are configured. kafkastore.bootstrap.servers must have at least one endpoint matching kafkastore.security.protocol.
2023-02-06 22:33:07     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig.endpointsToBootstrapServers(SchemaRegistryConfig.java:686)
2023-02-06 22:33:07     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig.bootstrapBrokers(SchemaRegistryConfig.java:635)
2023-02-06 22:33:07     at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.kafkaClusterId(KafkaSchemaRegistry.java:1599)
2023-02-06 22:33:07     at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:175)
2023-02-06 22:33:07     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:71)
2023-02-06 22:33:07     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:90)
2023-02-06 22:33:07     at io.confluent.rest.Application.configureHandler(Application.java:285)
2023-02-06 22:33:07     at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:270)
2023-02-06 22:33:07     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
2023-02-06 22:33:07     at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
```

i'm on Windows 11 with WSL2 Ubuntu

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:22 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by pwmcintyre** [comment]
same results on macOS

```
$ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:09 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:34:44 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
